### ISSUE TITLE
Please tell me where app id and targetSdkVersion etc are

### ISSUE THREAD

**Issue by blazingdevil44** [iammert/AppLocker#1]
Cant find application id and targetSdkVersion and other stuff like that are

**Comment by blazingdevil44** [comment]
Nvm its in ma

**Comment by blazingdevil44** [comment]
I found app id its in manifest I think if I change it there i hope everything will be ok but Where is targetSdkVersion and other stuff like that

**Comment by iammert** [comment]
Use the GitHub search bar to find a keyword on the project.
